### ISSUE TITLE
DDP Support

### ISSUE THREAD

**Issue by guns2410** [apollostack/subscriptions-transport-ws#41]
Are we looking at **DDP support** than starting a web socket server on a different port. Adding DDP support will help people like me who want to rely on hosting services like **Galaxy** and build Apollo server on top of meteor.

**Comment by stubailo** [comment]
Galaxy doesn't do anything special for DDP, it will work just fine with this transport as well. I don't think it's a good idea to try to mix GraphQL subscriptions and DDP on the same connection since they work in very different ways. I don't think just holding open one more connection will be a significant problem, but we can revisit this if it turns out to be one.

**Comment by guns2410** [comment]
Sorry @stubailo this is not the right place to ask, but does galaxy support ports other than 80 & 443 maybe to start a web socket server on the same graphql server. I am planning to host my Apollo Server on Galaxy as it is a perfect fit for me.

**Comment by dobesv** [comment]
In case anyone arrives here researching this, you can add your apollo subscriptions websocket to the existing galaxy / meteor express server without opening a new port.
